name: TeamWorkflow

on:
  push:
    branches:
      - main

jobs:
  integration-delivery:
    # NOTICE: We're no longer running ubuntu latest, since it has some issues with TestCafe. We have degraded to version 22.04 in stead.
    runs-on: ubuntu-22.04
    environment: Test
    # NOTICE: Node-container anymore
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # NOTICE: In stead of the container we're setting up node like this.
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: latest

      - name: Install dependencies
        run: npm install

      - name: Build website
        run: npm run build

      - name: FTP delivery
        uses: SamKirkland/FTP-deploy-Action@4.3.3
        with: 
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: test/todo/
          local-dir: dist/

      - name: Inject test page URL
        run: echo "testPage=${{ secrets.TEST_PAGE_URL }}" >> $GITHUB_ENV

      - name: Run TestCafe Tests
        uses: DevExpress/testcafe-action@latest
        with:
          args: "chrome test/*"  

      - name: Store artifacts
        uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist/

  deployment:
    needs: integration-delivery
    runs-on: ubuntu-22.04
    environment: Live
    steps:
      - name: Load artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist/   

      - name: FTP deploy
        uses: SamKirkland/FTP-deploy-Action@4.3.3
        with: 
          server: ${{ vars.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          server-dir: live/todo/
          local-dir: dist/      